# Generated by Django 4.2.7 on 2025-07-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('location', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('main_image', models.ImageField(upload_to='properties/main/', verbose_name='Imagen Principal')),
                ('airbnb_link', models.URLField(blank=True, verbose_name='AirBnB link')),
                ('habitaciones', models.PositiveIntegerField(verbose_name='Habitaciones')),
                ('banos', models.PositiveIntegerField(verbose_name='Baños')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('discount', models.TextField(blank=True, verbose_name='Descuento Especial!')),
                ('imagenes', models.ImageField(blank=True, upload_to='properties/extra/', verbose_name='Imágenes')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
