# Generated by Django 4.2.7 on 2025-07-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Destacado'),
        ),
    ]
