# Generated by Django 4.2.7 on 2025-07-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='long_description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
    ]
