# Generated by Django 4.2.7 on 2025-07-25 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_long_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='imagenes',
        ),
        migrations.AlterField(
            model_name='property',
            name='long_description',
            field=models.TextField(blank=True, verbose_name='Descripción Larga'),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/extra/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Título de la imagen')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='properties.property')),
            ],
            options={
                'verbose_name': 'Imagen de Propiedad',
                'verbose_name_plural': 'Imágenes de Propiedades',
                'ordering': ['order'],
            },
        ),
    ]
