# Generated by Django 4.2.7 on 2025-07-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_property_imagenes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['order'], 'verbose_name': 'Imagen de Propiedad', 'verbose_name_plural': 'Imágenes de la propiedad'},
        ),
    ]
