# Generated by Django 4.2.7 on 2025-12-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_propertyimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='capacity',
            field=models.PositiveIntegerField(default=2, verbose_name='Capacidad (Personas)'),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
    ]
